"""Initial schema

Revision ID: 86dabfbf21c1
Revises: 
Create Date: 2025-06-10 21:34:09.380697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86dabfbf21c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user_extend_history')
    op.alter_column('auth_user_extend', 'uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               nullable=True)
    op.alter_column('auth_user_extend', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('auth_user_extend', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('auth_user_extend', 'is_staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('auth_user_extend', 'date_joined',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user_extend', 'date_joined',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False)
    op.alter_column('auth_user_extend', 'is_staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('auth_user_extend', 'is_superuser',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('auth_user_extend', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('auth_user_extend', 'uuid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               nullable=False)
    op.create_table('auth_user_extend_history',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('history_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('history_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('history_type', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('history_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uuid', mysql.CHAR(length=36), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=True),
    sa.Column('contact_no', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('token_version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
